### ISSUE TITLE
[Bug]: Application Capability Profiler changes AppxManifest.xml encoding

### ISSUE THREAD

**Issue by riverar** [microsoft/win32-app-isolation#32]
### Version

Windows vNext: 25375.1
Win32 App Isolation: 0.1.0
Developer mode enabled

### Repro Steps

1. Open the application manifest (appxmanifest.xml) in Notepad
2. Set the `encoding` attribute at the top of the file to `utf-16`
3. In Notepad, click File > Save as > and ensure the encoding is set to `utf-16 le`. Save on top of the existing file.
4. Follow ACP documentation to profile any application
5. After running `Get-ProfilingResults`, re-open the manfiest in Notepad
6. Observe the encoding does not match

### Unexpected Results

* Tool alters AppxManifest without my knowledge/confirmation
* Tool does not maintain original file encoding

**Comment by macruzco** [comment]
Thank you for spotting and reporting this bug @riverar !

It's been fixed in [Win32 app isolation v0.1.1](https://github.com/microsoft/win32-app-isolation/releases/tag/v0.1.1).

## Application Capability Profiler v0.1.1 (2023-06-29)
1. #32 patched.  Get-ProfilingResults to keep target manifest's encoding or, if encoding cannot be determined, warn the user and create a new file with the default encoding.
2. Support for Microsoft-only capabilities removed.
3. Support for capabilities that are incompatible with Win32 app isolation removed.
